name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  test:
    name: Cargo Test
    strategy: { matrix: { os: [ ubuntu-latest, macos-latest, windows-latest ] } }
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set git to not convert line endings
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: Swatinem/rust-cache@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Show Compiler Version
      run: rustc --version --verbose
    - run: cargo fmt --check
    - run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test --verbose
    - name: Make sure clean can run
      run: cargo run --features cli -- clean tests/examples -r
