name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy: { matrix: { os: [ ubuntu-latest, macos-latest ] } }
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-python@v3.0.0
      with:
        python-version: '3.10'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  # Windows needs powershell so we need to make a separate job for it
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-python@v3.0.0
      with:
        python-version: '3.10'
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      shell: powershell
      run: cargo test --verbose
