name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug

jobs:
  test:
    name: Cargo Test
    strategy: { matrix: { os: [ ubuntu-latest, macos-latest, windows-latest ] } }
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set git to not convert line endings
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - name: Setup Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: stable
        components: clippy
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Show Compiler Version
      run: rustc --version --verbose
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Test
      run: cargo test --verbose
    - name: Make sure clean can run
      run: cargo run --features cli -- clean tests/examples -r
